# Generated by Django 3.1.2 on 2020-11-02 15:35

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position_number'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=30)),
                ('college_or_club', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='teamimages/')),
                ('web_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number_of_url_and_email', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-number_of_url_and_email'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('contents', markdownx.models.MarkdownxField(help_text='To Write with Markdown format')),
                ('tags', models.ManyToManyField(blank=True, to='app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='NationalMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_romaji', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=200)),
                ('selected_year', models.DateField(auto_now=True)),
                ('rank', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='nationalimages/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_romaji', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='memberimages/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.position')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
