# Generated by Django 3.1.7 on 2022-02-27 02:56

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JFSACupMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='jfsacupimages/')),
            ],
        ),
        migrations.CreateModel(
            name='JFSACupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='file/%Y/%m/%d')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JFSACupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('thumnail', models.ImageField(null=True, upload_to='jfsacupresultimages/')),
                ('upload', models.FileField(upload_to='file/%Y/%m/%d')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-position_number'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='raceimages/')),
                ('race_info_url', models.URLField(blank=True)),
                ('entry_info_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=30)),
                ('college_or_club', models.CharField(max_length=10)),
                ('training_place', models.CharField(blank=True, max_length=50, null=True)),
                ('training_term', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='teamimages/')),
                ('web_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number_of_url_and_email', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-number_of_url_and_email'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumnail', models.ImageField(null=True, upload_to='newsimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('contents', mdeditor.fields.MDTextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='NationalMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_romaji', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=200)),
                ('selected_year', models.DateField(blank=True, null=True)),
                ('rank', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='nationalimages/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.team')),
            ],
            options={
                'ordering': ['-selected_year', 'rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_romaji', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='memberimages/')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.team')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.position')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('thumnail', models.ImageField(null=True, upload_to='eventimages/')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('event_url', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='app.Tag')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
