# Generated by Django 3.1.2 on 2020-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='thumnail',
            field=models.ImageField(null=True, upload_to='newsimages/'),
        ),
    ]
