# Generated by Django 3.1.2 on 2020-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newspost_thumnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
