# Generated by Django 3.1.7 on 2022-02-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220227_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jfsacupmedia',
            name='album',
        ),
        migrations.DeleteModel(
            name='JFSACupMediaAlbum',
        ),
    ]
