# Generated by Django 3.1.7 on 2022-02-28 12:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220227_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jfsacupmedia',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
