# Generated by Django 3.1.2 on 2020-11-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201106_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalmember',
            name='selected_year',
            field=models.DateField(null=True),
        ),
    ]
