# Generated by Django 3.1.2 on 2020-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201117_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='nationalmember',
            options={'ordering': ['-selected_year', 'rank', 'name']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-position_number']},
        ),
        migrations.AddField(
            model_name='team',
            name='training_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='training_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
