# Generated by Django 3.1.6 on 2021-03-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210208_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumnail', models.ImageField(null=True, upload_to='eventimages/')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('event_url', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='app.Tag')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
