# Generated by Django 3.1.6 on 2021-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
