# Generated by Django 3.1.6 on 2021-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210307_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
