# Generated by Django 3.1.7 on 2021-11-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210307_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalmember',
            name='selected_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
