# Generated by Django 3.1.7 on 2021-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211129_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalmember',
            name='selected_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
