# Generated by Django 3.1.7 on 2022-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211129_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='raceimages/')),
                ('race_info_url', models.URLField(blank=True)),
                ('entry_info_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
