# Generated by Django 3.1.7 on 2022-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='JFSACupMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='jfsacupimages/')),
            ],
        ),
        migrations.CreateModel(
            name='JFSACupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='file/%Y/%m/%d')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JFSACupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='file/%Y/%m/%d')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['month']},
        ),
    ]
