# Generated by Django 3.1.7 on 2022-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220218_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='jfsacupresult',
            name='thumnail',
            field=models.ImageField(null=True, upload_to='jfsacupresultimages/'),
        ),
    ]
