# Generated by Django 3.1.7 on 2022-02-25 03:14

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_jfsacupresult_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='contents',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
    ]
